publishdir = "docs"
enableEmoji = true
  

baseurl = "https://infominer.id/web-work/"
title = "Webwork.tools"
copyright = "⧉ <a href='https://creativecommons.org/publicdomain/zero/1.0/'>Website Content Creative Commons (CC0 1.0) Public Domain</a> by <a href='https://infominer.id'>Infominer</a>. ⧉ Powered by <a href='https://themes.gohugo.io/indigo/'>Indigo</a> via <a href='https://github.com/gohugoio/hugo/releases/tag/v0.51'>Hugo</a> and <a href='https://infominer.id/gh-pages-starter-pack.html'>Github Pages</a>."
languageCode = "en-gb"
theme = "indigo"
paginate = 3

[params]
  Author = "Infominer"
  description = "Resources for Independent Webworkers: Web-Publishing, SEO, Static Site Generators, Ubuntu, Git, Practical Crypto."
  Subtitle = "Independent Web-Work and Skyscraper Publishing"
  Avatar = "images/infominer.svg"
  Biography = "Full-Time Crypto-Curation and Histories ⧉ #Bitcoin #Blockchain #DecentralizedID ⧉ Research, Publishing, #WebWork #Indieweb ⧉"
  ShowBio = true
  PermalinkText = "🔗"

  # Contact/social-network identifiers for social icons
  EmailAddress = "infominer@protonmail.com"
  GitHubUser = "infominer33"
  GitLabUser = "infominer33"
  KeybaseUser = "infominer"
  MicroBlogUser = "infominer"
  RedditUser = "infominer33"
  StackOverflowUser = "infominer33"
  TwitterUser = "infominer33"

  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]  
    EmailAddress = "infominer@protonmail.com"
    GitHubUser = "infominer33"
    TwitterUser = "infominer33"
    MicroBlogUser = "infominer"
    Country = "Stateless"
    City = "Marginalized"

  [params.twitter]
    card = "summary_image_large"
    site = "@infominer33"
    creator = "@infominer33"
