- menu_name: "Feeds"

- name: "feed.xml"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "atom.xml"
  url: "/atom.xml"
  title: "Subscribe to Atom Feed"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
